"""m1

Revision ID: 516ef161202
Revises: d3d1ded6cc
Create Date: 2016-01-27 02:42:21.816636

"""

# revision identifiers, used by Alembic.
revision = '516ef161202'
down_revision = 'd3d1ded6cc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
