"""start

Revision ID: d3d1ded6cc
Revises: 48d805d7e9
Create Date: 2016-01-26 13:34:16.729628

"""

# revision identifiers, used by Alembic.
revision = 'd3d1ded6cc'
down_revision = '48d805d7e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
